### ISSUE TITLE
rviz和gazebo显示不对，也不能控制

### ISSUE THREAD

**Issue by JeffXu1** [legubiao/quadruped_ros2_control#11]
按照1.2 Gazebo Classic Simulator (ROS2 Humble)这个步骤进行测试，系统是Ubuntu22 + ROS Humble Gazebo Classic
但是显示的不对,使用ros2 run keyboard_input keyboard_input命令之后也不能控制，已经在root模式下
![截图 2024-10-31 14-05-49](https://github.com/user-attachments/assets/50e71e08-77e1-4211-8c55-bed06fbdb4aa)
![截图 2024-10-31 14-06-28](https://github.com/user-attachments/assets/5e74a741-7573-477b-b912-7b72942872de)
![截图 2024-10-31 14-08-27](https://github.com/user-attachments/assets/6ae4869c-6e19-4110-8d4c-e0577248b5d5)

**Comment by legubiao** [comment]
有按照keyboard input的readme尝试控制吗？此外，我看报错路径有个xxgo_description，似乎不是我的项目里的内容？

**Comment by legubiao** [comment]
显示倒是看起来没问题，rviz和gazebo中的是同步的。得让机器人站起来才是readme中的效果

**Comment by legubiao** [comment]
如果没有更多的反馈，我会在一天后关闭这个议题
