### ISSUE TITLE
ocs2控制器trot步态下会打滑

### ISSUE THREAD

**Issue by yzyyyyy2048** [legubiao/quadruped_ros2_control#17]
非常感谢大佬的开源工作！我运行ocs2控制器后进入trot步态，没有给速度指令的情况下踏几步就会出现类似足底打滑的情况，有时会摔倒，请问会是pc性能原因影响到了求解器的解算吗？

**Comment by legubiao** [comment]
有可能，你可以先尝试下原版的ocs2的demo的表现。此外，如果你是ubuntu22，可以提高控制器的频率到500，mpc保持100

**Comment by yzyyyyy2048** [comment]
原版的ocs2表现还是挺正常的，我看求解时间也比较正常
![Uploading 截图 2024-12-13 20-58-45.png…]()

**Comment by yzyyyyy2048** [comment]
![截图 2024-12-13 21-13-23](https://github.com/user-attachments/assets/e2073b5b-7476-4b7e-8adf-75b414bf1c81)
这个频率提上去吗
