### ISSUE TITLE
ROS2 control can not run normally

### ISSUE THREAD

**Issue by hhsssjejs** [legubiao/quadruped_ros2_control#3]
I have installed unetree_mujoco according to the readme file, and successfully compiled the code from the two repositories "ocs2_ros2" and "quadruped_ros2_control". After starting the simulation ./unitree_mujoco, I ran the controller program, ros2 launch go2_description unitree_guide.launch.py, but ROS2 control did not seem to start, and it kept printing the following content in a loop：

![Uploading 09h26m36s时间2024年10月 9日.png…]()

**Comment by hhsssjejs** [comment]
![09h26m36s时间2024年10月 9日](https://github.com/user-attachments/assets/f980f37c-6f3a-4b9b-aa8f-2cd51744fc81)

**Comment by legubiao** [comment]
I noticed that in your log, it required to enable real-time kernel. You can follow the instruction to enable it and then have another try.

**Comment by legubiao** [comment]
![截图 2024-10-09 22-50-25](https://github.com/user-attachments/assets/8fc8429d-abd6-4761-bdcd-bb84b989f864)

Here is a screenshot of successful launch

**Comment by HJY2918** [comment]
I have the same problem when running the code. Is it right to follow the website: https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html to enable my real-time kernel? I have tried, but still the same.
Do I need  to improve the Ubuntu to the Ubuntu Pro?

**Comment by legubiao** [comment]
ubuntu pro is not essential as I also using normal version. Can you try the official demo of ros2-control to validate whether ros2-control can work?

**Comment by HJY2918** [comment]
![image](https://github.com/user-attachments/assets/46289d71-4f3b-4566-a6c8-e7f2b6ed7056)

I enable the real-time kernel, but still "Could not contact service /controller_manager/list_controllers".
I can run the ros2-control-demo(https://github.com/ros-controls/ros2_control_demos/tree/humble) successfully.

**Comment by legubiao** [comment]
What‘s your system and ros version？ I‘ check later using WSL. Now you can try to modified the launch file.

**Comment by HJY2918** [comment]
My version is as follows:
Ubuntu 22.04 LTS
ros2-humble

**Comment by legubiao** [comment]
I fix the issue. In ros2 humble, the launch config for controller manager required extra 'mapping'  item, like this:
```
    controller_manager = Node(
        package="controller_manager",
        executable="ros2_control_node",
        parameters=[robot_controllers],
        output="both",
        remappings=[
            ("~/robot_description", "/robot_description"),
        ],
    )

```

In ros2 jazzy this step no longer required.  I add this config at the go2_description/launch/unitree_guide.launch.py.

**Comment by HJY2918** [comment]
Thank you very much!!!! 
I successfully solved this problem!!
