### ISSUE TITLE
Did

### ISSUE THREAD

**Issue by Wichun-dot** [legubiao/quadruped_ros2_control#5]

**Comment by Wichun-dot** [comment]
Sorry for my inappropriate behavior. I just want to know whether this project can run in the Ubuntu20 ros2-foxy or not, since I have met many problemsl

**Comment by legubiao** [comment]
I only tested this project under ubuntu 22 and 24. But in theory I think it can run under Ubuntu  20 with some modifications. If you insist to run it in foxy, my suggestion is testing under 24 in Virtual Machine to understand how it works, then fork your Ubuntu 20 version.
