### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by Wichun-dot** [legubiao/quadruped_ros2_control#8]
你好，我在运行ros2 launch unitree_guide_controller mujoco.launch.py时，出现了如下问题，该如何解决呢？
![image](https://github.com/user-attachments/assets/f808f1c2-da5a-4aa3-b5f4-0d388068af45)

**Comment by legubiao** [comment]
unitree_sdk2和你系统安装的ros2的cyclonedds有冲突，导致启动不起来。你可以先尝试在不使用sudo权限的情况下能不能启动unitree_mujoco
